version: "2"
services:
  server1:
    build: server
    ports:
    - "3000:3000"
    volumes:
    - "./shared_volume:/shared_volume"
    restart: always
    environment:
      port: 3000
      name: 'Server1'
  server2:
    build: server
    ports:
    - "5000:5000"
    volumes:
    - "./shared_volume:/shared_volume"
    environment:
      port: 5000
      name: 'Server2'
  