apiVersion: apps/v1
kind: Deployment
metadata:
  name: server1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server1
  template:
    metadata:
      labels:
        app: server1
    spec:
      containers:
        - name: server1
          image: nirgeier/server1
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: server1
  labels:
    run: server1
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: server1
